// Generated from the verified Alloha browser probe. Keep this payload platform-neutral.
var ALLOHA_BROWSER_SCRIPT = [
    "        (function(){",
    "            function isPlayer(value) {",
    "                return value && (",
    "                    typeof value.api === \"function\" ||",
    "                    (value.media && typeof value.media.querySelectorAll === \"function\" && \"quality\" in value)",
    "                );",
    "            }",
    "            function labelOf(item) {",
    "                if (typeof item === \"string\") return item;",
    "                if (typeof item === \"number\") return String(item);",
    "                if (item && typeof item === \"object\") {",
    "                    return item.title || item.label || item.name || item.quality || item.text || item.value || item.size || \"\";",
    "                }",
    "                return String(item || \"\");",
    "            }",
    "            function findPlayer(win) {",
    "                var names = [\"player\", \"Player\", \"playerjs\", \"pl\"];",
    "                for (var i = 0; i < names.length; i++) {",
    "                    try {",
    "                        var candidate = win[names[i]];",
    "                        if (isPlayer(candidate)) return candidate;",
    "                    } catch (e) {}",
    "                }",
    "                try {",
    "                    var elementPlayer = win.document && win.document.getElementById(\"player\");",
    "                    if (isPlayer(elementPlayer)) return elementPlayer;",
    "                } catch (e) {}",
    "                for (var key in win) {",
    "                    try {",
    "                        if (isPlayer(win[key])) return win[key];",
    "                    } catch (e) {}",
    "                }",
    "                return null;",
    "            }",
    "            function addLabels(target, raw) {",
    "                if (!raw) return;",
    "                if (typeof raw === \"string\") {",
    "                    raw.split(\",\").forEach(function(item){ addLabels(target, item); });",
    "                    return;",
    "                }",
    "                if (Array.isArray(raw)) {",
    "                    raw.forEach(function(item){ addLabels(target, item); });",
    "                    return;",
    "                }",
    "                if (typeof raw.length === \"number\" && typeof raw !== \"function\") {",
    "                    for (var i = 0; i < raw.length; i++) addLabels(target, raw[i]);",
    "                    return;",
    "                }",
    "                target.push(labelOf(raw));",
    "            }",
    "            function normalize(labels) {",
    "                var known = {240:true,360:true,480:true,540:true,720:true,1080:true,1440:true,2160:true};",
    "                var result = {};",
    "                labels.forEach(function(label){",
    "                    var text = String(label || \"\").replace(/<[^>]+>/g, \"\").trim();",
    "                    var match = text.match(/\\d{3,4}/);",
    "                    if (!match) return;",
    "                    var quality = parseInt(match[0], 10);",
    "                    if (known[quality]) result[quality] = String(quality);",
    "                });",
    "                return Object.keys(result)",
    "                    .map(function(value){ return parseInt(value, 10); })",
    "                    .sort(function(a, b){ return a - b; })",
    "                    .map(function(value){ return String(value); });",
    "            }",
    "            function collectDomLabels(win, player) {",
    "                var labels = [];",
    "                var roots = [];",
    "                if (player && player.media) roots.push(player.media);",
    "                if (win.document) roots.push(win.document);",
    "                for (var rootIndex = 0; rootIndex < roots.length; rootIndex++) {",
    "                    var root = roots[rootIndex];",
    "                    try {",
    "                        var sourceNodes = root.querySelectorAll(\"source[size][src]\");",
    "                        for (var i = 0; i < sourceNodes.length; i++) {",
    "                            labels.push(sourceNodes[i].getAttribute(\"size\"));",
    "                        }",
    "                    } catch (e) {}",
    "                    try {",
    "                        var qualityNodes = root.querySelectorAll(",
    "                            \"[data-allplay='quality'], [name='quality'], [role='menuitemradio'], [data-quality], [quality]\"",
    "                        );",
    "                        for (var j = 0; j < qualityNodes.length; j++) {",
    "                            labels.push(",
    "                                qualityNodes[j].getAttribute(\"value\") ||",
    "                                qualityNodes[j].getAttribute(\"data-quality\") ||",
    "                                qualityNodes[j].getAttribute(\"quality\") ||",
    "                                qualityNodes[j].getAttribute(\"aria-label\") ||",
    "                                qualityNodes[j].textContent",
    "                            );",
    "                        }",
    "                    } catch (e) {}",
    "                }",
    "                return normalize(labels);",
    "            }",
    "            function collectPlayerLabels(player) {",
    "                var labels = [];",
    "                try { addLabels(labels, player.config && player.config.quality && player.config.quality.options); } catch (e) {}",
    "                try { addLabels(labels, player.options && player.options.quality); } catch (e) {}",
    "                try { addLabels(labels, player.config && player.config.hlsSource); } catch (e) {}",
    "                try { addLabels(labels, player.config && player.config.sources); } catch (e) {}",
    "                try { addLabels(labels, player.sources); } catch (e) {}",
    "                return normalize(labels);",
    "            }",
    "            function collectApiLabels(player) {",
    "                var labels = [];",
    "                try {",
    "                    if (player && typeof player.api === \"function\") {",
    "                        addLabels(labels, player.api(\"qualities\"));",
    "                    }",
    "                } catch (e) {}",
    "                try {",
    "                    if (player && player.media && typeof player.media.querySelectorAll === \"function\") {",
    "                        addLabels(labels, collectDomLabels(window, player));",
    "                    }",
    "                } catch (e) {}",
    "                return normalize(labels);",
    "            }",
    "            function playCurrent(win, player) {",
    "                try { player.api(\"play\"); } catch (e) {}",
    "                try {",
    "                    var video = win.document && win.document.querySelector(\"video\");",
    "                    if (video) video.play().catch(function(){});",
    "                } catch (e) {}",
    "            }",
    "            function switchByVideoSource(win, quality) {",
    "                try {",
    "                    var source = win.document && win.document.querySelector(\"source[size='\" + quality + \"'][src]\");",
    "                    var video = win.document && win.document.querySelector(\"video\");",
    "                    if (!source || !video) return false;",
    "                    video.src = source.getAttribute(\"src\");",
    "                    video.load();",
    "                    video.play().catch(function(){});",
    "                    return true;",
    "                } catch (e) {",
    "                    return false;",
    "                }",
    "            }",
    "",
    "            var frame = document.querySelector(\"iframe\");",
    "            var win = frame && frame.contentWindow ? frame.contentWindow : window;",
    "            var player = findPlayer(win);",
    "            if (!player) return \"no-player\";",
    "",
    "            var qualities = collectDomLabels(win, player);",
    "            if (!qualities.length) qualities = collectPlayerLabels(player);",
    "            if (!qualities.length) qualities = collectApiLabels(player);",
    "            if (!qualities.length) {",
    "                playCurrent(win, player);",
    "                HibikiResolver.done();",
    "                return JSON.stringify([]);",
    "            }",
    "",
    "            var index = 0;",
    "            function switchNext() {",
    "                if (index >= qualities.length) {",
    "                    HibikiResolver.done();",
    "                    return;",
    "                }",
    "                var quality = qualities[index++];",
    "                HibikiResolver.quality(quality);",
    "                try {",
    "                    var numericQuality = parseInt(quality, 10);",
    "                    if (numericQuality && typeof player.quality !== \"undefined\") {",
    "                        player.quality = numericQuality;",
    "                    } else if (typeof player.api === \"function\") {",
    "                        try {",
    "                            player.api(\"quality\", numericQuality || quality);",
    "                        } catch (e) {",
    "                            player.api(\"quality\", index - 1);",
    "                        }",
    "                    } else if (numericQuality) {",
    "                        switchByVideoSource(win, numericQuality);",
    "                    }",
    "                    try {",
    "                        frame.contentWindow.postMessage(JSON.stringify({api:\"quality\", value:numericQuality}), \"*\");",
    "                        frame.contentWindow.postMessage(JSON.stringify({api:\"quality\", value:index - 1}), \"*\");",
    "                    } catch (e) {}",
    "                } catch (e) {}",
    "                playCurrent(win, player);",
    "                setTimeout(switchNext, 1500);",
    "            }",
    "            switchNext();",
    "        })();",
    "    ",
].join("\n");

var Provider = {
    browserScript: function (linkJson) { return ALLOHA_BROWSER_SCRIPT; }
};

